# Immuatable parameters
TILE_SIZE = 32
RESOLUTION = (1920, 1080)
FPS = 60
GRID_LENGTH = 30
SURFACE_WIDTH = TILE_SIZE * GRID_LENGTH * 2
SURFACE_HEIGHT = TILE_SIZE * GRID_LENGTH + TILE_SIZE * 2
TICKS_PER_DAY = 50
IMAGE_PATH = 'assets/graphics/'

# Mutable parameters
NB_BOB = 10
NB_SPAWN_FOOD = 20

FOOD_ENERGY = 100

BOB_SPAWN_ENERGY = 100
BOB_MAX_ENERGY = 200
# BOB_BIRTH_ENERGY = 50

PERCEPTION_FLAT_PENALTY = 1/5
MEMORY_FLAT_PENALTY = 1/5

DEFAULT_VELOCITY = 1
DEFAULT_MASS = 1
DEFAULT_VISION = 4
DEFAULT_MEMORY_POINT = 0

VAR_MASS = 0.1
VAR_VELO = 0.1
VAR_VISION = 1
VAR_MEMORY_POINT = 1

SELF_REPRODUCTION = True
SEXUAL_REPRODUCTION = True