TILE_SIZE = 32

GRID_LENGTH = 30
SURFACE_WIDTH = TILE_SIZE * GRID_LENGTH * 2
SURFACE_HEIGHT = TILE_SIZE * GRID_LENGTH + TILE_SIZE * 2
TICKS_PER_DAY = 50
IMAGE_PATH = 'assets/graphics/'

FOOD_MAX_ENERGY = 200

NB_BOB = 5
NB_SPAWN_FOOD = 10
FPS = 60

VISION = 4

VAR_MASS = 0.1
VAR_VELO = 0.1

REPRODUCTION = True
PARTHENOGENESIS = True